#!/bin/bash

USER_HOME=$(eval echo ~$USER)
FILE_DST="$USER_HOME/.config/custom_theme"

change_theme() {
    themes=(`lookandfeeltool -l`)

    themes_count=${#themes[@]}
    theme=${themes[$(( ( RANDOM % ${themes_count} )))]}
    echo "$theme" > $FILE_DST
}


CUSTOM_THEME=$(<"$USER_HOME/.config/custom_theme")
lookandfeeltool -a $CUSTOM_THEME;
lookandfeeltool -a $CUSTOM_THEME

change_theme 

